# What is the definition of pandas?

Pandas is an open-source Python library designed for data manipulation and analysis. It provides powerful, easy-to-use data structures such as Series and DataFrame that allow users to work efficiently with structured data like tables, spreadsheets, and time-series data. Pandas supports reading and writing data from multiple file formats, including CSV, Excel, JSON, and databases. It offers tools for cleaning, transforming, filtering, aggregating, and analyzing data with minimal code. Built on top of NumPy, pandas is widely used in data science, machine learning, finance, and research because it simplifies handling real-world, messy datasets.

# Data Frame

A DataFrame is a two-dimensional data structure in pandas that organizes data into rows and columns, similar to a spreadsheet or database table. It allows efficient storage, manipulation, filtering, and analysis of structured data, making it easy to work with real-world datasets in Pytho

In [2]:
# Create a DataFrame
import pandas as pd

df = pd.DataFrame([[1 ,2, 3], [4,5,6] , [7,8,9]])
# This is used to print all the rows and columns
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [3]:
df = pd.DataFrame([[1 ,2, 3], [4,5,6] , [7,8,9]] , columns=["A" ,"B" ,"C"])
# This is used to print first five rows of the dataset
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
# To assign rows values with special index.
df = pd.DataFrame([[1 ,2, 3], [4,5,6] , [7,8,9]] , columns=["A" ,"B" ,"C"] , index= ["x" , "y" ,"z"])
# This is used to print first five rows of the dataset
df.head()

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [5]:
df.head(1) # To print single row

   A  B  C
x  1  2  3

In [6]:
df.tail(1) # To print the last rows of the dataset.

   A  B  C
z  7  8  9

In [7]:
df.columns.tolist() # To shows  name of the columns in list format.

['A', 'B', 'C']

In [8]:
df.index.tolist() # To shows the list of index

['x', 'y', 'z']

In [9]:
df.info() # To display all the information of the dataset.

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [10]:
df.nunique() # To check the number of unique value.

A    3
B    3
C    3
dtype: int64

In [11]:
# To check the number of unique value in the perticular columns
df["A"].unique()

array([1, 4, 7])

In [12]:
df.shape # To find out the number of rows and columns dataset have.

(3, 3)

In [13]:
df.size # To finds total number of items.

9

# Real world Data analysis using pandas

In [14]:
#To read the csv data
coffee = pd.read_csv(r"B:\DataScienceTutorial\Dataset1\coffee.csv")
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [15]:
# To print first five rows of the dataset
coffee.head(5)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

# Parquet in dataset:

Parquet is a columnar storage file format designed to efficiently store large datasets. Unlike row-based formats like CSV, Parquet stores data column by column, which allows for:

- Faster data reading for specific columns

- Better compression and reduced storage size

- Preservation of data types (integers, floats, strings, dates, etc.)

- It is widely used in data engineering, analytics, and big data platforms like Spark, Hive, and pandas.

In [16]:
results = pd.read_parquet(r"B:\DataScienceTutorial\Dataset1\results.parquet")
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [22]:
olympics_data = pd.read_excel(r"B:\DataScienceTutorial\Dataset1\olympics-data.xlsx", sheet_name="results")
olympics_data.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

# Openpyxl

openpyxl is a Python library used to read, write, and manipulate Excel files with the .xlsx extension.

In [23]:
bios = pd.read_csv(r"B:\DataScienceTutorial\Dataset1\bios.csv")
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

# Accessing data with pandas.

In [24]:
coffee.head(5)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [25]:
coffee.tail(5)

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [ ]:
coffee.sample(10) # Randow change at every run

          Day Coffee Type  Units Sold
7    Thursday       Latte          30
13     Sunday       Latte          35
1      Monday       Latte          15
5   Wednesday       Latte          25
10   Saturday    Espresso          45
6    Thursday    Espresso          40
8      Friday    Espresso          45
9      Friday       Latte          35
0      Monday    Espresso          25
12     Sunday    Espresso          45

In [38]:
coffee.sample(10 , random_state=1)# Random data display of rows and columns but there is no change at every run.

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [39]:
coffee.loc[0] # loc["Rows" , "Columns"]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [40]:
coffee.loc[[0,1,6]]

        Day Coffee Type  Units Sold
0    Monday    Espresso          25
1    Monday       Latte          15
6  Thursday    Espresso          40

In [41]:
coffee.loc[0:3] # Slicing

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [ ]:
coffee.loc[0:] # This shows row starts from 0 till end

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [44]:
coffee.loc[3:7 , ["Day" , "Units Sold"]]

         Day  Units Sold
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25
6   Thursday          40
7   Thursday          30

In [ ]:
coffee.iloc[3:7 , [0,2]] # Column name is treat as index in iloc

         Day  Units Sold
3    Tuesday          20
4  Wednesday          35
5  Wednesday          25
6   Thursday          40

In [47]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [48]:
coffee.loc[1 ,"Units Sold"] = 30
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          30
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [49]:
coffee.loc[0 ,"Coffee Type"] = "Latte"
coffee

          Day Coffee Type  Units Sold
0      Monday       Latte          25
1      Monday       Latte          30
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
coffee.iloc[1 , 2] = 90 # The columns value is used as index rather than name of the column.
coffee

          Day Coffee Type  Units Sold
0      Monday       Latte          25
1      Monday       Latte          90
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
coffee.iloc[0:4 , 2] = 87 # To assign the number of unit sold with new value
coffee.head()

         Day Coffee Type  Units Sold
0     Monday       Latte          87
1     Monday       Latte          87
2    Tuesday    Espresso          87
3    Tuesday       Latte          87
4  Wednesday    Espresso          35

In [53]:
coffee["Day"] # To access the data of the perticular column.

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [55]:
coffee.Day # If column name as a single word

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [59]:
coffee.sort_values("Units Sold" ,ascending= False) # The any of the columns numerical values

          Day Coffee Type  Units Sold
0      Monday       Latte          87
1      Monday       Latte          87
2     Tuesday    Espresso          87
3     Tuesday       Latte          87
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
11   Saturday       Latte          35
4   Wednesday    Espresso          35
13     Sunday       Latte          35
9      Friday       Latte          35
7    Thursday       Latte          30
5   Wednesday       Latte          25

In [62]:
coffee.sort_values(["Units Sold" , "Coffee Type"] , ascending=[1,1])

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
2     Tuesday    Espresso          87
0      Monday       Latte          87
1      Monday       Latte          87
3     Tuesday       Latte          87

In [65]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("\n \n")

0
Day            Monday
Coffee Type     Latte
Units Sold         87
Name: 0, dtype: object



1
Day            Monday
Coffee Type     Latte
Units Sold         87
Name: 1, dtype: object



2
Day             Tuesday
Coffee Type    Espresso
Units Sold           87
Name: 2, dtype: object



3
Day            Tuesday
Coffee Type      Latte
Units Sold          87
Name: 3, dtype: object



4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object



5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object



6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object



7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object



8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object



9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object



10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object



11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object



12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object



13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

## Filtering Data

In [66]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
bios.loc[bios["height_cm"] > 215 , ["height_cm" , "weight_kg"]] # Conditon and selected columns

        height_cm  weight_kg
5089        220.0      112.0
5583        217.0      106.0
5673        221.0      114.0
5716        218.0      110.0
5781        223.0      102.0
5796        218.0       93.0
6223        216.0      105.0
6270        216.0      135.0
6409        216.0      111.0
6420        218.0      141.0
6504        220.0      135.0
6722        216.0      137.0
6937        216.0      107.0
6978        223.0      122.0
7074        217.0      106.0
7188        220.0      110.0
7281        217.0      115.0
7376        218.0      115.0
52608       217.0      102.0
82100       218.0      110.0
89070       226.0      141.0
89075       221.0      137.0
107408      219.0      113.0
112312      217.0      110.0
112332      216.0      115.0
112337      218.0      110.0
118663      216.0      113.0
118676      219.0      104.0
120266      221.0      110.0
121694      216.0      110.0
123850      216.0      107.0
130460      218.0      115.0
130461      217.0       95.0
138671      216.0      107.0
139365      218.0        NaN

In [72]:
bios[(bios["height_cm"] > 215) & (bios["born_country"] == "USA")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [ ]:
bios[bios["name"].str.contains("Keith")]# Case sensitive

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [76]:
bios[bios["name"].str.contains("keith | patrick" , case= False)] # Case sensitivity of the contains

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
116580,117975,Elizabeth Patrick,1985-03-02,Melbourne,Victoria,AUS,Australia,155.0,50.0,NaN
121749,123764,Jaele Patrick,1988-03-04,Lilydale,Victoria,AUS,Australia,164.0,59.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN

In [83]:
bios[bios["born_country"].isin(["USA" , "France", "England"]) & (bios["name"].str.startswith("Keith"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

In [90]:
bios.query('born_country == "USA" and born_city == "Seattle"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
11030,11088,David Halpern,1955-08-18,Seattle,Washington,USA,United States,178.0,79.0,NaN
12800,12870,Todd Trewin,1958-04-20,Seattle,Washington,USA,United States,180.0,75.0,NaN
15476,15583,Scott McKinley,1968-10-15,Seattle,Washington,USA,United States,183.0,75.0,NaN
29079,29293,Joyce Tanac,1950-09-27,Seattle,Washington,USA,United States,156.0,49.0,NaN
31135,31371,Bill Kuhlemeier,1908-01-14,Seattle,Washington,USA,United States,NaN,NaN,2001-07-08
...,...,...,...,...,...,...,...,...,...,...
133392,136331,Hans Struzyna,1989-03-31,Seattle,Washington,USA,United States,188.0,91.0,NaN
135448,138662,Maude Davis Crossland,2003-03-19,Seattle,Washington,USA,Colombia,NaN,NaN,NaN
136993,140229,Jenell Berhorst,2003-12-13,Seattle,Washington,USA,United States,NaN,NaN,NaN
143507,147159,Nevin Harrison,2002-06-02,Seattle,Washington,USA,United States,175.0,73.0,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN

## Adding And Removing Columns

In [91]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday       Latte          87
1     Monday       Latte          87
2    Tuesday    Espresso          87
3    Tuesday       Latte          87
4  Wednesday    Espresso          35

In [92]:
coffee["Price"] = 4.99
coffee.head()

         Day Coffee Type  Units Sold  Price
0     Monday       Latte          87   4.99
1     Monday       Latte          87   4.99
2    Tuesday    Espresso          87   4.99
3    Tuesday       Latte          87   4.99
4  Wednesday    Espresso          35   4.99

In [93]:
import numpy as np
coffee["New_price"] = np.where(coffee["Coffee Type"] =="Espresso" , 3.99 , 4.99)

In [94]:
coffee.head()

         Day Coffee Type  Units Sold  Price  New_price
0     Monday       Latte          87   4.99       4.99
1     Monday       Latte          87   4.99       4.99
2    Tuesday    Espresso          87   4.99       3.99
3    Tuesday       Latte          87   4.99       4.99
4  Wednesday    Espresso          35   4.99       3.99

In [97]:
coffee.drop(columns= "Price" , inplace=True)
coffee

          Day Coffee Type  Units Sold  New_price
0      Monday       Latte          87       4.99
1      Monday       Latte          87       4.99
2     Tuesday    Espresso          87       3.99
3     Tuesday       Latte          87       4.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       4.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       4.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       4.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       4.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       4.99

In [100]:
coffee["Revenue"] = coffee["Units Sold"] * coffee["New_price"]
coffee.head()

         Day Coffee Type  Units Sold  New_price  Revenue
0     Monday       Latte          87       4.99   434.13
1     Monday       Latte          87       4.99   434.13
2    Tuesday    Espresso          87       3.99   347.13
3    Tuesday       Latte          87       4.99   434.13
4  Wednesday    Espresso          35       3.99   139.65

In [103]:
coffee.rename(columns={"New_price" : "Price"} , inplace=True )

In [105]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte          87   4.99   434.13
1     Monday       Latte          87   4.99   434.13
2    Tuesday    Espresso          87   3.99   347.13
3    Tuesday       Latte          87   4.99   434.13
4  Wednesday    Espresso          35   3.99   139.65

In [107]:
bios_new = bios.copy()
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [108]:
bios_new["First_name"] = bios_new["name"].str.split(" ").str[0]
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,First_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [ ]:
bios_new.query('First_name == "Keith"') #  To display the rows and column of dataset that has first name keith

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,First_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [112]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  First_name    145500 non-null  object
dtypes: float64(2), int64(1), object(1), str(7)
memory usage: 19.6+ MB

In [ ]:
bios_new["born_datetime"] = pd.to_datetime(bios_new["born_date"]) # Converting the column born_date from string to date time
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,First_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17

In [115]:
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  str
 2   born_date      143693 non-null  str
 3   born_city      110908 non-null  str
 4   born_region    110908 non-null  str
 5   born_country   110908 non-null  str
 6   NOC            145499 non-null  str
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   str
 10  First_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(7)
memory usage: 20.7+ MB

In [ ]:
bios_new["born_year"] = bios_new["born_datetime"].dt.year # To get year from date format
bios_new[["name","born_year"]]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [ ]:
bios_new["born_month"] = bios_new["born_datetime"].dt.month # To get month from date format
bios_new[["name","born_datetime" , "born_year" ,"born_month"]]

                         name born_datetime  born_year  born_month
0       Jean-François Blanchy    1886-12-12     1886.0        12.0
1              Arnaud Boetsch    1969-04-01     1969.0         4.0
2                Jean Borotra    1898-08-13     1898.0         8.0
3             Jacques Brugnon    1895-05-11     1895.0         5.0
4                Albert Canet    1878-04-17     1878.0         4.0
...                       ...           ...        ...         ...
145495      Polina Luchnikova    2002-01-30     2002.0         1.0
145496    Valeriya Merkusheva    1999-09-20     1999.0         9.0
145497        Yuliya Smirnova    1998-05-08     1998.0         5.0
145498         André Foussard    1899-05-19     1899.0         5.0
145499          Bill Phillips    1913-07-15     1913.0         7.0

[145500 rows x 4 columns]

In [122]:
bios_new["born_day"] = bios_new["born_datetime"].dt.day # To get day from date format
bios_new[["name","born_datetime" , "born_year" ,"born_month" ,"born_day"]]

                         name born_datetime  born_year  born_month  born_day
0       Jean-François Blanchy    1886-12-12     1886.0        12.0      12.0
1              Arnaud Boetsch    1969-04-01     1969.0         4.0       1.0
2                Jean Borotra    1898-08-13     1898.0         8.0      13.0
3             Jacques Brugnon    1895-05-11     1895.0         5.0      11.0
4                Albert Canet    1878-04-17     1878.0         4.0      17.0
...                       ...           ...        ...         ...       ...
145495      Polina Luchnikova    2002-01-30     2002.0         1.0      30.0
145496    Valeriya Merkusheva    1999-09-20     1999.0         9.0      20.0
145497        Yuliya Smirnova    1998-05-08     1998.0         5.0       8.0
145498         André Foussard    1899-05-19     1899.0         5.0      19.0
145499          Bill Phillips    1913-07-15     1913.0         7.0      15.0

[145500 rows x 5 columns]

In [125]:
bios_new.to_csv(r"B:\DataScienceTutorial\Dataset1\bios_new.csv" , index=False)

In [ ]:
bios["height_category"] = bios["height_cm"].apply(lambda x : "Short" if x < 165 else ("Average" if x < 185 else "Tall") )

In [127]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall

In [128]:
def categorize_athelete(row):
    if row["height_cm"] < 175 and row["weight_kg"] < 70:
        return "LightWeight"
    elif row["height_cm"] < 185 or row["weight_kg"] <= 80:
        return "Midweight"
    else:
        return "HeavyWeight"
    

bios["weight_category"] = bios.apply(categorize_athelete , axis = 1) # axis = 1 is for row

In [129]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,HeavyWeight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Midweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Midweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,LightWeight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,HeavyWeight

In [132]:
bios = pd.read_csv(r"B:\DataScienceTutorial\Dataset1\bios.csv")
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

## Merging and Concatenation.

In [133]:
nocs = pd.read_csv(r"B:\DataScienceTutorial\Dataset1\noc_regions.csv")
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [135]:
bios_merge = pd.merge(bios , nocs , left_on="born_country" , right_on="NOC" , how= "left" , suffixes =["bios" , "nocdf"])

In [137]:
bios_merge.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocdf,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [138]:
bios_merge.rename(columns={"region" : "born_country_full"} , inplace=True)

In [139]:
bios_merge.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocdf,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [140]:
usa = bios[bios["born_country"] == "USA"].copy()
gbr = bios[bios["born_country"] == "GBR"].copy()

In [142]:
new_df = pd.concat([usa , gbr])
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN

In [143]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [145]:
combined_df = pd.merge(results , bios , on="athlete_id" , how="left")

In [146]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

| Parameter             | Meaning                          |
| --------------------- | -------------------------------- |
| `left`, `right`       | DataFrames to merge              |
| `how`                 | Type of join                     |
| `on`                  | Column(s) to join on             |
| `left_on`, `right_on` | Different column names           |
| `suffixes`            | Resolve overlapping column names |

**Inner join**

- Keeps only matching keys

**Left Jion**

✔ All rows from left
✔ Matching rows from right
✔ Missing matches → NaN

**Right join**

✔ All rows from right

**Outer join**

✔ Keeps all rows
✔ Missing matches → NaN

## Handling Null Values

In [147]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte          87   4.99   434.13
1     Monday       Latte          87   4.99   434.13
2    Tuesday    Espresso          87   3.99   347.13
3    Tuesday       Latte          87   4.99   434.13
4  Wednesday    Espresso          35   3.99   139.65

In [150]:
# To insert nan to the rows and columns
coffee.loc[[0,1], "Units Sold"] = np.nan

In [151]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte         NaN   4.99   434.13
1     Monday       Latte         NaN   4.99   434.13
2    Tuesday    Espresso        87.0   3.99   347.13
3    Tuesday       Latte        87.0   4.99   434.13
4  Wednesday    Espresso        35.0   3.99   139.65

In [153]:
#coffee.isna()  # It will just true or false based on value present or not

In [154]:
coffee.isna().sum()# To count the number of nulll values present

Day            0
Coffee Type    0
Units Sold     2
Price          0
Revenue        0
dtype: int64

In [156]:
#coffee.fillna(30)

In [158]:
coffee.fillna(coffee["Units Sold"].mean())
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte         NaN   4.99   434.13
1     Monday       Latte         NaN   4.99   434.13
2    Tuesday    Espresso        87.0   3.99   347.13
3    Tuesday       Latte        87.0   4.99   434.13
4  Wednesday    Espresso        35.0   3.99   139.65

In [160]:
coffee.loc[[0,1] , "Units Sold"] =15
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte        15.0   4.99   434.13
1     Monday       Latte        15.0   4.99   434.13
2    Tuesday    Espresso        87.0   3.99   347.13
3    Tuesday       Latte        87.0   4.99   434.13
4  Wednesday    Espresso        35.0   3.99   139.65

In [162]:
coffee.loc[[2,3] ,"Units Sold"] = np.nan
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte        15.0   4.99   434.13
1     Monday       Latte        15.0   4.99   434.13
2    Tuesday    Espresso         NaN   3.99   347.13
3    Tuesday       Latte         NaN   4.99   434.13
4  Wednesday    Espresso        35.0   3.99   139.65

In [168]:
coffee["Units Sold"] = coffee["Units Sold"].interpolate()

In [169]:
coffee.head() # Interpolate replace nan value by nearest value of the rows.

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte   15.000000   4.99   434.13
1     Monday       Latte   15.000000   4.99   434.13
2    Tuesday    Espresso   21.666667   3.99   347.13
3    Tuesday       Latte   28.333333   4.99   434.13
4  Wednesday    Espresso   35.000000   3.99   139.65

In [ ]:
# coffee.dropna() # To drop the rows having missing values

In [ ]:
# coffee.dropna(subsets = ["Units sold"] , inplace = True)

In [170]:
coffee[coffee["Units Sold"].isna()]

Empty DataFrame
Columns: [Day, Coffee Type, Units Sold, Price, Revenue]
Index: []

In [171]:
coffee[coffee["Units Sold"].notna()]

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday       Latte   15.000000   4.99   434.13
1      Monday       Latte   15.000000   4.99   434.13
2     Tuesday    Espresso   21.666667   3.99   347.13
3     Tuesday       Latte   28.333333   4.99   434.13
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   4.99   124.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   4.99   149.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   4.99   174.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   4.99   174.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   4.99   174.65

## Aggregating Data

In [172]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [174]:
bios["born_city"].value_counts() # Display unique value and their frequency.

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [178]:
bios[bios["born_country"] == "USA"]["born_region"].value_counts().tail()

born_region
South Dakota     27
West Virginia    24
Delaware         22
North Dakota     16
Wyoming          14
Name: count, dtype: int64

In [ ]:
bios[bios["born_country"] == "USA"]["born_region"].value_counts().head()

In [179]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte   15.000000   4.99   434.13
1     Monday       Latte   15.000000   4.99   434.13
2    Tuesday    Espresso   21.666667   3.99   347.13
3    Tuesday       Latte   28.333333   4.99   434.13
4  Wednesday    Espresso   35.000000   3.99   139.65

In [181]:
coffee.groupby(coffee["Coffee Type"])["Units Sold"].sum()

Coffee Type
Espresso    231.666667
Latte       218.333333
Name: Units Sold, dtype: float64

In [182]:
coffee.groupby(coffee["Coffee Type"])["Price"].mean()

Coffee Type
Espresso    3.99
Latte       4.99
Name: Price, dtype: float64

In [183]:
coffee.groupby(coffee["Day"])["Units Sold"].sum()

Day
Friday       80.0
Monday       30.0
Saturday     80.0
Sunday       80.0
Thursday     70.0
Tuesday      50.0
Wednesday    60.0
Name: Units Sold, dtype: float64

In [188]:
coffee.groupby(coffee["Coffee Type"]).agg({"Units Sold" : 'sum' , "Price" : 'mean' ,})

             Units Sold  Price
Coffee Type
Espresso     231.666667   3.99
Latte        218.333333   4.99

In [190]:
coffee.groupby(["Coffee Type", "Day"]).agg({
    "Units Sold": "sum",
    "Price": "mean"
})

                       Units Sold  Price
Coffee Type Day
Espresso    Friday      45.000000   3.99
            Saturday    45.000000   3.99
            Sunday      45.000000   3.99
            Thursday    40.000000   3.99
            Tuesday     21.666667   3.99
            Wednesday   35.000000   3.99
Latte       Friday      35.000000   4.99
            Monday      30.000000   4.99
            Saturday    35.000000   4.99
            Sunday      35.000000   4.99
            Thursday    30.000000   4.99
            Tuesday     28.333333   4.99
            Wednesday   25.000000   4.99

**Pivot**

In pandas, pivot() is used to reshape data — specifically to turn unique values from one column into new columns, similar to an Excel Pivot Table (but simpler).

In [191]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday       Latte   15.000000   4.99   434.13
1     Monday       Latte   15.000000   4.99   434.13
2    Tuesday    Espresso   21.666667   3.99   347.13
3    Tuesday       Latte   28.333333   4.99   434.13
4  Wednesday    Espresso   35.000000   3.99   139.65

In [196]:
pivot = coffee.pivot_table(
    index="Day",
    columns="Coffee Type",
    values="Revenue",
    aggfunc="sum"   # or 'mean', 'max', etc.
)

In [197]:
pivot.head()

Coffee Type  Espresso   Latte
Day
Friday         179.55  174.65
Monday            NaN  868.26
Saturday       179.55  174.65
Sunday         179.55  174.65
Thursday       159.60  149.70

In [ ]:
results_numpy = pd.read_csv(r"B:\DataScienceTutorial\Dataset1\results.csv")
results_arrow = pd.read_csv(r"B:\DataScienceTutorial\Dataset1\results.csv" , engine="pyarrow" , dtype_backend="pyarrow")

In [198]:
pd.__version__

'3.0.0'